test_000:
	glslViewer test_000.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver test_000.yaml

test_001:
	glslViewer test_001.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver test_001.yaml

nanoKontrol2:
	glslViewer nanoKontrol2.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver nanoKontrol2.yaml

orthoRemote:
	glslViewer orthoRemote.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver orthoRemote.yaml