test_000:
	glslViewer test_000.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver test_000.yaml

test_001:
	glslViewer test_001.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver test_001.yaml

test_002:
	glslViewer test_002.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver test_002.yaml

test_003:
	glslViewer test_003.frag -p 8000 -l -e cursor,off &
	sleep 1 && midigyver test_003.yaml

blender_frames:
	blender blender_frames.blend &
	sleep 1 && midigyver blender_frames.yaml