language: c++

os:
  - linux

compiler:
  - gcc

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
      && sudo apt-get update -qq \
      && if [ "$CXX" == "g++" ]; then
        sudo apt-get install -qq g++-4.9 && export CXX="g++-4.9" CC="gcc-4.9"
      fi
    fi
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - test/run-tests

matrix:
  exclude:
  - os: linux
    compiler: clang
